export interface InventionEffect {
  starCoinsPerHour?: number;
  multiplier?: number;
  coinsPerAnswer?: number;
}

export interface Invention {
  id: string;
  name: string;
  emoji: string;
  description: string;
  tier: 1 | 2 | 3 | 4;
  levelRequired: number;
  recipe: Record<string, number>;
  effect: InventionEffect;
}

export const INVENTIONS: Invention[] = [
  {
    id: "lunar_lamp",
    name: "Lunar Lamp",
    emoji: "🌛",
    description: "Moonstone wired into a glow ring",
    tier: 1,
    levelRequired: 3,
    recipe: { moon: 1 },
    effect: { starCoinsPerHour: 3 },
  },
  {
    id: "rust_drill",
    name: "Rust Drill",
    emoji: "⛏️",
    description: "Forged from Martian iron dust",
    tier: 1,
    levelRequired: 3,
    recipe: { mars: 1 },
    effect: { starCoinsPerHour: 4 },
  },
  {
    id: "acid_flask",
    name: "Acid Flask",
    emoji: "🧪",
    description: "Sulfur stone dissolved in curiosity",
    tier: 1,
    levelRequired: 4,
    recipe: { venus: 1 },
    effect: { starCoinsPerHour: 3 },
  },
  {
    id: "graphite_pencil",
    name: "Graphite Pencil",
    emoji: "✏️",
    description: "Writes the right answer every time",
    tier: 1,
    levelRequired: 4,
    recipe: { mercury: 1 },
    effect: { multiplier: 1.05 },
  },
  {
    id: "sapphire_lens",
    name: "Sapphire Lens",
    emoji: "🔭",
    description: "Deep-space optics, surprisingly affordable",
    tier: 1,
    levelRequired: 5,
    recipe: { neptune: 1 },
    effect: { starCoinsPerHour: 5 },
  },
  {
    id: "gravity_boots",
    name: "Gravity Boots",
    emoji: "👟",
    description: "Walk on walls, earn coins on Earth",
    tier: 2,
    levelRequired: 6,
    recipe: { moon: 1, mars: 1 },
    effect: { starCoinsPerHour: 12 },
  },
  {
    id: "solar_amplifier",
    name: "Solar Amplifier",
    emoji: "☀️",
    description: "Amplifies both the sun and your score",
    tier: 2,
    levelRequired: 6,
    recipe: { mercury: 1, venus: 1 },
    effect: { starCoinsPerHour: 10, multiplier: 1.08 },
  },
  {
    id: "frost_lens",
    name: "Frost Lens",
    emoji: "🌬️",
    description: "Ice-cold optics from the outer planets",
    tier: 2,
    levelRequired: 7,
    recipe: { uranus: 1, neptune: 1 },
    effect: { starCoinsPerHour: 18 },
  },
  {
    id: "gas_reactor",
    name: "Gas Reactor",
    emoji: "⚗️",
    description: "Jupiter gas meets Saturn rings — volatile combo",
    tier: 2,
    levelRequired: 8,
    recipe: { jupiter: 1, saturn: 1 },
    effect: { starCoinsPerHour: 22 },
  },
  {
    id: "topaz_crown",
    name: "Topaz Crown",
    emoji: "👑",
    description: "Earn a coin for every right answer",
    tier: 2,
    levelRequired: 8,
    recipe: { jupiter: 1, moon: 1 },
    effect: { coinsPerAnswer: 1 },
  },
  {
    id: "deep_compass",
    name: "Deep Compass",
    emoji: "🧭",
    description: "Navigates the market as well as the cosmos",
    tier: 2,
    levelRequired: 9,
    recipe: { neptune: 1, mercury: 1 },
    effect: { starCoinsPerHour: 15 },
  },
  {
    id: "star_map",
    name: "Star Map",
    emoji: "🗺️",
    description: "Charts every star coin in the universe",
    tier: 3,
    levelRequired: 10,
    recipe: { moon: 1, jupiter: 1, saturn: 1 },
    effect: { starCoinsPerHour: 35 },
  },
  {
    id: "plasma_engine",
    name: "Plasma Engine",
    emoji: "🔥",
    description: "Faster thinking, hotter score",
    tier: 3,
    levelRequired: 11,
    recipe: { mars: 1, jupiter: 1, mercury: 1 },
    effect: { starCoinsPerHour: 30, multiplier: 1.1 },
  },
  {
    id: "ring_forge",
    name: "Ring Forge",
    emoji: "💍",
    description: "Saturn's rings melted into pure income",
    tier: 3,
    levelRequired: 11,
    recipe: { saturn: 2, moon: 1 },
    effect: { starCoinsPerHour: 40 },
  },
  {
    id: "nebula_jar",
    name: "Nebula Jar",
    emoji: "🫙",
    description: "A jar of bottled nebula — smells like profit",
    tier: 3,
    levelRequired: 12,
    recipe: { uranus: 1, neptune: 1, venus: 1 },
    effect: { starCoinsPerHour: 38 },
  },
  {
    id: "crimson_shield",
    name: "Crimson Shield",
    emoji: "🛡️",
    description: "Each answer shielded with bonus coins",
    tier: 3,
    levelRequired: 13,
    recipe: { mars: 2, venus: 1 },
    effect: { coinsPerAnswer: 2 },
  },
  {
    id: "ice_core",
    name: "Ice Core",
    emoji: "🧊",
    description: "Compressed outer-planet ice, worth a fortune",
    tier: 4,
    levelRequired: 14,
    recipe: { uranus: 2, neptune: 1 },
    effect: { starCoinsPerHour: 45 },
  },
  {
    id: "cosmic_engine",
    name: "Cosmic Engine",
    emoji: "🚀",
    description: "Four-planet combustion. Maximum output",
    tier: 4,
    levelRequired: 15,
    recipe: { mars: 1, jupiter: 1, saturn: 1, neptune: 1 },
    effect: { starCoinsPerHour: 60 },
  },
  {
    id: "void_prism",
    name: "Void Prism",
    emoji: "🔮",
    description: "Bends spacetime — and your point total",
    tier: 4,
    levelRequired: 16,
    recipe: { uranus: 1, neptune: 1, mercury: 1, moon: 1 },
    effect: { starCoinsPerHour: 55, multiplier: 1.15 },
  },
  {
    id: "grand_orrery",
    name: "Grand Orrery",
    emoji: "⚙️",
    description: "All eight planets orbiting in perfect harmony",
    tier: 4,
    levelRequired: 17,
    recipe: { moon: 1, mercury: 1, venus: 1, mars: 1, jupiter: 1, saturn: 1, uranus: 1, neptune: 1 },
    effect: { starCoinsPerHour: 100 },
  },
  {
    id: "infinity_core",
    name: "Infinity Core",
    emoji: "✨",
    description: "The ultimate invention — coins and multipliers forever",
    tier: 4,
    levelRequired: 18,
    recipe: { moon: 2, mars: 2, jupiter: 2, saturn: 2 },
    effect: { coinsPerAnswer: 3, multiplier: 1.2 },
  },
];
