export interface CelestialBody {
  id: string;
  name: string;
  emoji: string;
  radius: number;
  captureRadius: number;
  mu: number;
  soi: number;
  color: string;
  x: number;
  y: number;
  isSun?: boolean;
  isEarth?: boolean;
  gem?: string;
  gemName?: string;
  launchCost: number;
  travelHint: string;
}

export const SOLAR_SYSTEM: CelestialBody[] = [
  {
    id: "sun",
    name: "Sun",
    emoji: "☀️",
    radius: 200,
    captureRadius: 0,
    mu: 2000,
    soi: 999999,
    color: "#FFE033",
    x: 0,
    y: 0,
    isSun: true,
    launchCost: 0,
    travelHint: "",
  },
  {
    id: "mercury",
    name: "Mercury",
    emoji: "🪨",
    radius: 28,
    captureRadius: 90,
    mu: 400,
    soi: 280,
    color: "#9E9E9E",
    x: 1300,
    y: -900,
    gem: "🩶",
    gemName: "Graphite Crystal",
    launchCost: 20,
    travelHint: "~8 sec",
  },
  {
    id: "venus",
    name: "Venus",
    emoji: "🌑",
    radius: 50,
    captureRadius: 130,
    mu: 800,
    soi: 420,
    color: "#E8B86D",
    x: -400,
    y: -1600,
    gem: "🟡",
    gemName: "Sulfur Stone",
    launchCost: 35,
    travelHint: "~14 sec",
  },
  {
    id: "earth",
    name: "Earth",
    emoji: "🌍",
    radius: 65,
    captureRadius: 120,
    mu: 5000,
    soi: 700,
    color: "#1B6B3A",
    x: 2000,
    y: 0,
    isEarth: true,
    launchCost: 0,
    travelHint: "",
  },
  {
    id: "moon",
    name: "Moon",
    emoji: "🌕",
    radius: 38,
    captureRadius: 110,
    mu: 900,
    soi: 330,
    color: "#AAAAAA",
    x: 2380,
    y: -420,
    gem: "🌙",
    gemName: "Moonstone",
    launchCost: 8,
    travelHint: "~4 sec",
  },
  {
    id: "mars",
    name: "Mars",
    emoji: "🔴",
    radius: 36,
    captureRadius: 110,
    mu: 600,
    soi: 380,
    color: "#C1440E",
    x: 4500,
    y: 1200,
    gem: "❤️‍🔥",
    gemName: "Fire Ruby",
    launchCost: 50,
    travelHint: "~18 sec",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    emoji: "🟠",
    radius: 110,
    captureRadius: 250,
    mu: 5000,
    soi: 1100,
    color: "#C88B3A",
    x: -5200,
    y: 900,
    gem: "💛",
    gemName: "Golden Topaz",
    launchCost: 150,
    travelHint: "~38 sec",
  },
  {
    id: "io",
    name: "Io",
    emoji: "🟡",
    radius: 22,
    captureRadius: 75,
    mu: 260,
    soi: 210,
    color: "#F6C447",
    x: -4880,
    y: 590,
    gem: "🟨",
    gemName: "Sulfur Moon Shard",
    launchCost: 165,
    travelHint: "~40 sec",
  },
  {
    id: "europa",
    name: "Europa",
    emoji: "⚪",
    radius: 21,
    captureRadius: 75,
    mu: 240,
    soi: 205,
    color: "#BFE8FF",
    x: -5540,
    y: 570,
    gem: "⬜",
    gemName: "Ice Line Crystal",
    launchCost: 170,
    travelHint: "~42 sec",
  },
  {
    id: "ganymede",
    name: "Ganymede",
    emoji: "🟤",
    radius: 30,
    captureRadius: 92,
    mu: 330,
    soi: 260,
    color: "#A78B72",
    x: -5680,
    y: 1220,
    gem: "🟫",
    gemName: "Grooved Stone",
    launchCost: 185,
    travelHint: "~45 sec",
  },
  {
    id: "callisto",
    name: "Callisto",
    emoji: "⚫",
    radius: 28,
    captureRadius: 88,
    mu: 300,
    soi: 245,
    color: "#8F8790",
    x: -4860,
    y: 1250,
    gem: "⬛",
    gemName: "Crater Pearl",
    launchCost: 195,
    travelHint: "~48 sec",
  },
  {
    id: "saturn",
    name: "Saturn",
    emoji: "🪐",
    radius: 85,
    captureRadius: 200,
    mu: 4000,
    soi: 950,
    color: "#E8D5A3",
    x: 5800,
    y: -5500,
    gem: "💎",
    gemName: "Diamond Ring",
    launchCost: 200,
    travelHint: "~55 sec",
  },
  {
    id: "uranus",
    name: "Uranus",
    emoji: "🔵",
    radius: 65,
    captureRadius: 170,
    mu: 2500,
    soi: 800,
    color: "#7FD8E8",
    x: -3000,
    y: -8000,
    gem: "🩵",
    gemName: "Frost Aquamarine",
    launchCost: 300,
    travelHint: "~1.2 min",
  },
  {
    id: "neptune",
    name: "Neptune",
    emoji: "🌀",
    radius: 60,
    captureRadius: 160,
    mu: 3000,
    soi: 850,
    color: "#4169E1",
    x: 2500,
    y: 10500,
    gem: "💙",
    gemName: "Deep Space Sapphire",
    launchCost: 450,
    travelHint: "~2 min",
  },
];

export const EARTH_BODY = SOLAR_SYSTEM.find((b) => b.isEarth)!;
export const SUN_BODY = SOLAR_SYSTEM.find((b) => b.isSun)!;
